// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = "https://journalism-society.vercel.app";
const SITE_NAME = "Journalism Society";

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Journalism Society — Right of Reply. In Full.",
    template: "%s | Journalism Society",
  },
  description:
    "Journalism Society is an independent public record platform for publishing Right of Reply responses, corrections, and evidence to counter inaccurate or false reporting in India.",
  keywords: [
    "right of reply",
    "journalism accountability",
    "public record",
    "media corrections",
    "press freedom India",
    "fact checking",
    "defamation response",
    "media accountability",
    "journalism society",
    "dockets",
  ],
  authors: [{ name: "Journalism Society", url: SITE_URL }],
  creator: "Journalism Society",
  publisher: "Journalism Society",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "Journalism Society — Right of Reply. In Full.",
    description:
      "An independent public record platform ensuring every public claim has a documented, permanent response. Audi alteram partem.",
    images: [
      {
        url: `${SITE_URL}/og-image.jpg`,
        width: 1200,
        height: 630,
        alt: "Journalism Society — Right of Reply. In Full.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@JournalismSoc",
    creator: "@JournalismSoc",
    title: "Journalism Society — Right of Reply. In Full.",
    description:
      "An independent public record platform ensuring every public claim has a documented, permanent response.",
    images: [`${SITE_URL}/og-image.jpg`],
  },
  verification: {
    google: "your-google-site-verification-token",
  },
  alternates: {
    canonical: SITE_URL,
  },
};

// Global Organization JSON-LD schema
const orgSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Journalism Society",
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description:
    "An independent public record platform for Right of Reply responses, corrections, and accountability in journalism.",
  foundingDate: "2024",
  areaServed: "IN",
  contactPoint: {
    "@type": "ContactPoint",
    email: "submit@journalismsociety.org",
    contactType: "editorial",
    availableLanguage: ["English"],
  },
  sameAs: [],
};

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Journalism Society",
  url: SITE_URL,
  description: "Right of Reply. In Full. — India's independent public record platform.",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en-IN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#1e2d4a" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}